Command line arguments were ['seed_and_invoke.py', '456910573', 'phase5b']
Starting at 00:53:03.555438
Using seed 456910573 for phase5b
Running at  00:53:03.555438
